# Generated by Django 3.2.2 on 2021-06-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intcoal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='habits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='thoughts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thought', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='intcoal',
            new_name='tasks',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='title',
            new_name='task',
        ),
    ]
