# Generated by Django 3.2.2 on 2021-06-03 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intcoal', '0002_auto_20210603_0657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='habits',
        ),
        migrations.DeleteModel(
            name='thoughts',
        ),
    ]
